#grafana-deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: maya-grafana
  name: maya-grafana
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: maya-grafana
    spec:
      securityContext:
        fsGroup: 107
      containers:
      - image: grafana/grafana:4.6.3
        name: master-grafana
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
          - name: GF_AUTH_BASIC_ENABLED
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: "false"
        volumeMounts:
          - name: config-volume
            mountPath: "/etc/grafana"
          - name: maya-grafana-store
            mountPath: /var/lib/grafana
            # /var contains directories to hold grafana db, logs etc..,
        ### Commenting below livenessProbe resource as it is causing issues behind ingress-proxy.
        #livenessProbe:
        #  httpGet:
        #    path: /
        #    port: 3000
        #  initialDelaySeconds: 30
        #  timeoutSeconds: 1
      volumes:
        - name: config-volume
          configMap:
            name: maya-grafana-cfgmap
        - name: maya-grafana-store
          gcePersistentDisk:
            pdName: maya-pre-prod-grafana-disk 
            # in the gke, the disk should already be created in the cluster using the following command
            # gcloud compute disks create --size 200GB maya-stage-grafana-disk
            fsType: ext4
---
# grafana-service
apiVersion: v1
kind: Service
metadata:
  name: maya-grafana-service
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: maya-grafana
