apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: maya-ui-deployment
spec:
 replicas: 1
 template:
   metadata:
     labels:
       app : maya-ui
   spec:
     containers:
       - name: maya-ui
         image: index.docker.io/mayadataio/maya-ui:alpha-r3-3ec89d1
         imagePullPolicy: Always
         ports:
         - containerPort: 80
     imagePullSecrets:
       - name: mayadatasecret
---
apiVersion: v1
kind: Service
metadata:
 labels:
   app: maya-ui
 name: maya-ui
spec:
 ports:
 - name: maya-ui
   port: 80
   protocol: TCP
 selector:
   app: maya-ui
